# Generated by Django 2.1.5 on 2020-03-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
